### ISSUE TITLE
502 bad gateway on website...

### ISSUE THREAD

**Issue by karanganesan** [schollz/hostyoself#1]

**Comment by wpcarro** [comment]
I'm getting this too. I'm quite interested in trying this out!

**Comment by kompiuter** [comment]
@wpcarro you could always run it locally

**Comment by gvc14** [comment]
@kompiuter how?

**Comment by schollz** [comment]
Its up!

**Comment by griffincodes** [comment]
@schollz its down again :(
http://prntscr.com/of7y8z
