### ISSUE TITLE
How do I host from command line?

### ISSUE THREAD

**Issue by griffincodes** [schollz/hostyoself#15]
I was wondering if someone could tell me how I host from the command line? Thanks in advance!

**Comment by schollz** [comment]
Did you try this: https://github.com/schollz/hostyoself#host-from-the-command-line ?

**Comment by griffincodes** [comment]
I have Windows and I couldn't get Docker to work for some reason.

**Comment by schollz** [comment]
I can't help with Docker.

I suggest using a release: https://github.com/schollz/hostyoself/releases
