### ISSUE TITLE
Homebrew install script

### ISSUE THREAD

**Issue by dmuth** [schollz/hostyoself#3]
Would like to see this available as a Homebrew install script for OS/X.

If you like, I'd be willing to take a crack at that this weekend. :-)

-- Doug

**Comment by schollz** [comment]
Hi @dmuth,

I don't do Mac so I can't test it but it should already be done (via @goreleaser): https://github.com/schollz/homebrew-tap/blob/master/Formula/hostyoself.rb

Try it out and let me know :)

**Comment by dmuth** [comment]
That seemed to work--I could get the app installed and run it, however hostyoself.com is currently throwing HTTP 502 errors so I can't fully test.

Either way, I will throw a PR your way for the README. :-)

-- Doug
