### ISSUE TITLE
Does not work on Firefox 68.0 on Android 5.1.1

### ISSUE THREAD

**Issue by daveloyall** [schollz/hostyoself#4]
Hi.  After selecting a document on Firefox 68.0 on Android 5.1.1, the "Your file is available at:" text never appears.

**Comment by schollz** [comment]
Thanks, I'm aware of this one. I don't have a fix for it yet (because I don't know yet whats going wrong).

**Comment by daveloyall** [comment]
schollz, hm, before I opened this Issue, I used the 'report problem' feature in Firefox mobile.  Apparently that resulted in the creation of this Issue: https://github.com/webcompat/web-bugs/issues/35215 

I have taken information from that automatically ticket and reformatted it for legibility.  I hope this helps!

## Various facts
* browser: Firefox Mobile 68.0
* ua_header: Mozilla/5.0 (Android 5.1.1; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0
* mixed active content blocked: false
* image.mem.shared: true
* buildID: 20190703180654
* tracking content blocked: false
* gfx.webrender.blob-images: true
* hasTouchScreen: true
* mixed passive content blocked: false
* gfx.webrender.enabled: false
* gfx.webrender.all: false
* channel: nightly

## Last console messages
<pre>
[u'[JavaScript Error: "TypeError: file.webkitRelativePath is undefined" {
	file: "https://hostyoself.com/static/main.js" line: 54}]
		@https://hostyoself.com/static/main.js:54:13
		emit@https://hostyoself.com/static/dropzone.js:84:20
		@https://hostyoself.com/static/dropzone.js:1830:12
		setupHiddenFileInput/<@https://hostyoself.com/static/dropzone.js:1246:24',
u'[JavaScript Error: "TypeError: file.webkitRelativePath is undefined" {
	file: "https://hostyoself.com/static/main.js" line: 55}]
		@https://hostyoself.com/static/main.js:55:20
		emit@https://hostyoself.com/static/dropzone.js:84:20
		addFile@https://hostyoself.com/static/dropzone.js:1830:12
		setupHiddenFileInput/<@https://hostyoself.com/static/dropzone.js:1246:24']
</pre>

**Comment by schollz** [comment]
Hi @daveloyall 

Thanks for that, your logging did the trick. This should fix it: https://github.com/schollz/hostyoself/commit/47ef11549196402b97eea66eb03aabc5c98b3bd8

Its live now, so give it a try and let me know.

**Comment by daveloyall** [comment]
Duuuude, this is the coolest thing I've done with a smart phone since the "simulated Zippo" app.

https://hostyoself.com/boringbaboon/IMG_20190715_134308.jpg

Nice work, schollz!
