### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by LoganDark** [schollz/hostyoself#9]
You don't need MySQL, PHP, or Apache for a website. In fact I wouldn't use any one of those, _especially_ not MySQL. Not to mention that 'dynamic DNS' is not needed if your IP only changes once in a millennium.

And port forwarding isn't hard, and isn't even needed if you get a cloud server with its own dedicated IP for like $5/mo from DigitalOcean or somewhere else. And right now Hosting24 is offering their highest tier of shared hosting for $4 a month, which includes SSH access, and sure yeah MySQL and PHP if you insist.

![image](https://user-images.githubusercontent.com/4723091/61187053-ce7de700-a621-11e9-8112-153e989c146c.png)

:>

Shared access is no root access but VPSes aren't expensive :p

**Comment by schollz** [comment]
Thanks.
